---
# Workflow to build the documentation.
#
# - check the quality of the doc strings.
# - build doc and upload it as artifact.
#
# To run this check locally from the `doc` folder:
#
# .. code-block:: bash
#
#   $ cd ./doc
#   $ make html-strict
###
name: "DOCUMENTATION"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:

  build_and_deploy:

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Latex
      run: |
        sudo -E apt-get -yq update
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install \
            dvipng texlive-latex-base texlive-latex-extra
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        python -m pip install --progress-bar off matplotlib seaborn nilearn tensorboard
        python -m pip install --progress-bar off .
        python -m pip install --progress-bar off .[openbhb]
        python -m pip install --progress-bar off .[doc]
    - name: Compute documentation
      run: |
        cd ./doc
        make html-strict
        cd ..
    - name: Upload documentation as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-documentation
        retention-days: 15
        path: |
            doc/_build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
        destination_dir: dev

  build:

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref != 'refs/heads/main' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Latex
      run: |
        sudo apt-get update
        sudo apt install texlive-latex-extra
        sudo apt install dvipng
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        python -m pip install --progress-bar off matplotlib seaborn nilearn tensorboard
        python -m pip install --progress-bar off .
        python -m pip install --progress-bar off .[openbhb]
        python -m pip install --progress-bar off .[doc]
    - name: Compute documentation
      run: |
        cd ./doc
        make html-strict
    - name: Upload documentation as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-documentation
        retention-days: 7
        path: |
            doc/_build/html
