name: "TESTING"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pynose coverage[toml]
        python -m pip install --progress-bar off .[plugins,openbhb]
    - name: Run unit tests
      run: |
        nosetests --with-coverage --cover-package=nidl --verbosity=2
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        debug: true
        fail-on-error: true
